2022-05-24 18:12:25,159 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from /Users/Derek/.config/wandb/settings
2022-05-24 18:12:25,160 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from /Users/Derek/Desktop/hyperbolic_byol/wandb/settings
2022-05-24 18:12:25,160 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-05-24 18:12:25,160 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-05-24 18:12:25,160 WARNING MainThread:43768 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 884, in _input_request
    ident, reply = self.session.recv(self.stdin_socket, 0)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 803, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-776baadf643d>", line 4, in <module>
    wandb.init(config = args.__dict__, name = name)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1021, in init
    raise e
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 242, in setup
    _entity=kwargs.get("entity") or settings.entity,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 297, in _login
    wlogin.prompt_api_key()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 220, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 204, in _prompt_api_key
    no_create=self._settings.force if self._settings else None,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/apikey.py", line 120, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 842, in getpass
    password=True,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 889, in _input_request
    raise KeyboardInterrupt
KeyboardInterrupt
2022-05-24 18:12:25,161 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-05-24 18:12:25,162 INFO    MainThread:43768 [wandb_init.py:_log_setup():428] Logging user logs to /Users/Derek/Desktop/hyperbolic_byol/wandb/run-20220524_181225-9c8194i9/logs/debug.log
2022-05-24 18:12:25,162 INFO    MainThread:43768 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/Derek/Desktop/hyperbolic_byol/wandb/run-20220524_181225-9c8194i9/logs/debug-internal.log
2022-05-24 18:12:25,162 INFO    MainThread:43768 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb45c33aa90>
2022-05-24 18:12:25,163 INFO    MainThread:43768 [wandb_init.py:init():462] calling init triggers
2022-05-24 18:12:25,164 INFO    MainThread:43768 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {'dataset': 'cifar100', 'transform_kwargs': [{'brightness': 0.4, 'contrast': 0.4, 'saturation': 0.2, 'hue': 0.1, 'color_jitter_prob': 0.8, 'gray_scale_prob': 0.2, 'horizontal_flip_prob': 0.5, 'gaussian_prob': 1.0, 'solarization_prob': 0.0, 'crop_size': 32, 'min_scale': 0.08, 'max_scale': 1.0}, {'brightness': 0.4, 'contrast': 0.4, 'saturation': 0.2, 'hue': 0.1, 'color_jitter_prob': 0.8, 'gray_scale_prob': 0.2, 'horizontal_flip_prob': 0.5, 'gaussian_prob': 0.1, 'solarization_prob': 0.2, 'crop_size': 32, 'min_scale': 0.08, 'max_scale': 1.0}], 'num_crops_per_aug': [1, 1], 'batch_size': 256, 'num_workers': 4, 'optimizer': 'LARS', 'lr': 0.001, 'weight_decay': 1.5e-06, 'momentum': 0.9, 'classifier_lr': 0.01, 'classifier_weight_decay': 0, 'epochs': 200, 'warmup_epochs': 10, 'steps': 39062, 'warmup_steps': 1953, 'wd': 1.5e-05}
2022-05-24 18:12:25,164 INFO    MainThread:43768 [wandb_init.py:init():515] starting backend
2022-05-24 18:12:25,164 INFO    MainThread:43768 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-05-24 18:12:25,182 INFO    MainThread:43768 [backend.py:ensure_launched():217] starting backend process...
2022-05-24 18:12:25,205 INFO    MainThread:43768 [backend.py:ensure_launched():222] started backend process with pid: 43849
2022-05-24 18:12:25,215 INFO    MainThread:43768 [wandb_init.py:init():525] backend started and connected
2022-05-24 18:12:25,320 INFO    MainThread:43768 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-05-24 18:12:25,322 INFO    MainThread:43768 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-05-24 18:12:25,322 INFO    MainThread:43768 [wandb_init.py:init():596] updated telemetry
2022-05-24 18:12:25,518 INFO    MainThread:43768 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-05-24 18:12:28,191 INFO    MainThread:43768 [wandb_run.py:_on_init():1924] communicating current version
2022-05-24 18:12:28,302 INFO    MainThread:43768 [wandb_run.py:_on_init():1928] got version response 
2022-05-24 18:12:28,302 INFO    MainThread:43768 [wandb_init.py:init():662] starting run threads in backend
2022-05-24 18:12:33,350 INFO    MainThread:43768 [wandb_run.py:_console_start():1898] atexit reg
2022-05-24 18:12:33,357 INFO    MainThread:43768 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-05-24 18:12:33,360 INFO    MainThread:43768 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-05-24 18:12:33,365 INFO    MainThread:43768 [wandb_run.py:_redirect():1832] Redirects installed.
2022-05-24 18:12:33,365 INFO    MainThread:43768 [wandb_init.py:init():688] run started, returning control to user process
2022-05-24 18:12:33,366 INFO    MainThread:43768 [wandb_init.py:_pause_backend():341] pausing backend
2022-05-24 18:12:33,366 INFO    MainThread:43768 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-24 18:13:09,814 INFO    MainThread:43768 [wandb_init.py:_resume_backend():350] resuming backend
2022-05-24 18:13:13,534 INFO    MainThread:43768 [wandb_init.py:_pause_backend():341] pausing backend
2022-05-24 18:13:13,535 INFO    MainThread:43768 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-24 18:13:20,903 INFO    MainThread:43768 [wandb_init.py:_resume_backend():350] resuming backend
2022-05-24 18:13:22,423 INFO    MainThread:43768 [wandb_init.py:_pause_backend():341] pausing backend
2022-05-24 18:13:22,424 INFO    MainThread:43768 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-24 18:13:40,306 INFO    MainThread:43768 [wandb_init.py:_resume_backend():350] resuming backend
2022-05-24 18:13:40,327 INFO    MainThread:43768 [wandb_init.py:_pause_backend():341] pausing backend
2022-05-24 18:13:40,327 INFO    MainThread:43768 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-24 18:13:41,375 INFO    MainThread:43768 [wandb_init.py:_resume_backend():350] resuming backend
2022-05-24 18:13:41,433 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from /Users/Derek/.config/wandb/settings
2022-05-24 18:13:41,434 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from /Users/Derek/Desktop/hyperbolic_byol/wandb/settings
2022-05-24 18:13:41,434 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-05-24 18:13:41,434 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-05-24 18:13:41,434 WARNING MainThread:43768 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 884, in _input_request
    ident, reply = self.session.recv(self.stdin_socket, 0)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 803, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-776baadf643d>", line 4, in <module>
    wandb.init(config = args.__dict__, name = name)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1021, in init
    raise e
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 242, in setup
    _entity=kwargs.get("entity") or settings.entity,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 297, in _login
    wlogin.prompt_api_key()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 220, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 204, in _prompt_api_key
    no_create=self._settings.force if self._settings else None,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/apikey.py", line 120, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 842, in getpass
    password=True,
  File "/Users/Derek/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 889, in _input_request
    raise KeyboardInterrupt
KeyboardInterrupt
2022-05-24 18:13:41,437 INFO    MainThread:43768 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-05-24 18:13:41,438 INFO    MainThread:43768 [wandb_init.py:_log_setup():428] Logging user logs to /Users/Derek/Desktop/hyperbolic_byol/wandb/run-20220524_181341-1qrial81/logs/debug.log
2022-05-24 18:13:41,438 INFO    MainThread:43768 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/Derek/Desktop/hyperbolic_byol/wandb/run-20220524_181341-1qrial81/logs/debug-internal.log
2022-05-24 18:13:41,438 INFO    MainThread:43768 [wandb_init.py:init():462] calling init triggers
2022-05-24 18:13:41,439 INFO    MainThread:43768 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {'dataset': 'cifar100', 'transform_kwargs': [{'brightness': 0.4, 'contrast': 0.4, 'saturation': 0.2, 'hue': 0.1, 'color_jitter_prob': 0.8, 'gray_scale_prob': 0.2, 'horizontal_flip_prob': 0.5, 'gaussian_prob': 1.0, 'solarization_prob': 0.0, 'crop_size': 32, 'min_scale': 0.08, 'max_scale': 1.0}, {'brightness': 0.4, 'contrast': 0.4, 'saturation': 0.2, 'hue': 0.1, 'color_jitter_prob': 0.8, 'gray_scale_prob': 0.2, 'horizontal_flip_prob': 0.5, 'gaussian_prob': 0.1, 'solarization_prob': 0.2, 'crop_size': 32, 'min_scale': 0.08, 'max_scale': 1.0}], 'num_crops_per_aug': [1, 1], 'batch_size': 256, 'num_workers': 4, 'optimizer': 'LARS', 'lr': 0.001, 'weight_decay': 1.5e-06, 'momentum': 0.9, 'classifier_lr': 0.01, 'classifier_weight_decay': 0, 'epochs': 200, 'warmup_epochs': 10, 'steps': 39062, 'warmup_steps': 1953, 'wd': 1.5e-05}
2022-05-24 18:13:41,439 INFO    MainThread:43768 [wandb_init.py:init():482] re-initializing run, found existing run on stack: 9c8194i9
2022-05-24 18:13:41,442 INFO    MainThread:43768 [wandb_run.py:_finish():1685] finishing run dcaustin33/hyperbolic_byol/9c8194i9
2022-05-24 18:13:41,443 INFO    MainThread:43768 [jupyter.py:save_history():435] not saving jupyter history
2022-05-24 18:13:41,443 INFO    MainThread:43768 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-24 18:13:41,444 INFO    MainThread:43768 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-05-24 18:13:41,444 INFO    MainThread:43768 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-05-24 18:13:41,446 INFO    MainThread:43768 [wandb_run.py:_restore():1839] restore
2022-05-24 18:13:41,745 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 678
  total_bytes: 678
}

2022-05-24 18:13:42,173 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 678
  total_bytes: 678
}

2022-05-24 18:13:43,138 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 678
  total_bytes: 29964
}

2022-05-24 18:13:43,250 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 678
  total_bytes: 29964
}

2022-05-24 18:13:43,358 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29937
  total_bytes: 29964
}

2022-05-24 18:13:43,468 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29937
  total_bytes: 29964
}

2022-05-24 18:13:43,571 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29937
  total_bytes: 29964
}

2022-05-24 18:13:43,674 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:43,783 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:43,890 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:43,995 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:44,100 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:44,392 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}

2022-05-24 18:13:44,741 INFO    MainThread:43768 [wandb_run.py:_on_finish():1996] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 29964
  total_bytes: 29964
}
local_info {
}

2022-05-24 18:13:46,656 INFO    MainThread:43768 [wandb_run.py:_footer_history_summary_info():3104] rendering history
2022-05-24 18:13:46,657 INFO    MainThread:43768 [wandb_run.py:_footer_history_summary_info():3136] rendering summary
2022-05-24 18:13:46,664 INFO    MainThread:43768 [wandb_run.py:_footer_sync_info():3060] logging synced files
